### ISSUE TITLE
 spider.go第144行闭包go函数丢了参数名，导致req成为引用传参！

### ISSUE THREAD

**Issue by henrylee2cn** [hu17889/go_spider#12]
![image](https://cloud.githubusercontent.com/assets/10174178/6933311/dc33659c-d857-11e4-953a-f46627592b7c.png)
 
spider.go第144行闭包go函数丢了参数名，导致req成为引用传参！

**Comment by hu17889** [comment]
感谢提醒，正在修改，，有修改欢迎直接提交pull request

**Comment by sorawa** [comment]
已经修正了
